name: gscreen
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8.6
  - matplotlib==3.3.3
  - numpy=1.19.5
  - pandas==1.2.0
  - scikit-learn=0.23.2
  - scikit-optimize=0.8.1
  - scipy=1.6.0
  - seaborn==0.11.1
  - pip
  - pip:
      - mlflow==1.13.1
      - pandas-profiling==2.10.0
      - sweetviz==2.0.4
      - xgboost==1.3.1
      - yellowbrick==1.2
